version: '3'

vars:
  PROJECT_NAME: holiday-schedule

tasks:
  # デフォルトタスク: ビルド + デプロイ
  default:
    desc: Build and deploy to Cloudflare Pages
    cmds:
      - ./scripts/deploy.sh

  # ビルドのみ
  build:
    desc: Build for production
    cmds:
      - npm run build

  # デプロイのみ（カスタムスクリプトを使用）
  deploy:
    desc: Deploy to Cloudflare Pages using optimized script
    cmds:
      - ./scripts/deploy.sh
      
  # ローカル開発サーバー起動
  dev:
    desc: Start development server
    cmds:
      - npm run dev
      
  # アイコン生成
  icons:
    desc: Generate app icons
    cmds:
      - npm run generate-icons 