# Cloudflare Pagesの設定ファイル
name = "holiday-schedule"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]

# Pagesのビルド出力ディレクトリ
pages_build_output_dir = ".deploy"

# 本番環境の設定
[env.production]
name = "holiday-schedule-prod" 