# .cloudflare/pages.toml
[build]
command = "npm run pages:build"

[site]
bucket = ".deploy"

[compatibility_flags]
nodejs_compat = true

[env.production]
NODE_ENV = "production"

[env.staging]
NODE_ENV = "development"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
